# Generated by Django 4.1.7 on 2023-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0010_delivered_his_delv'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
