# Generated by Django 4.1.7 on 2023-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0011_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr_can_odr',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
