# Generated by Django 4.1.7 on 2023-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0013_com_can_odr_amount_delivered_his_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_can_odr',
            name='no',
            field=models.IntegerField(null=True),
        ),
    ]
