# Generated by Django 4.1.7 on 2023-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watercanapp', '0014_com_can_odr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_can_odr',
            name='no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
